all: koa toa

koa:
	@./run 1 $@
	@./run 5 $@
	@./run 10 $@
	@./run 20 $@
	@./run 50 $@
	@./run 100 $@

toa:
	@./run 1 $@
	@./run 5 $@
	@./run 10 $@
	@./run 20 $@
	@./run 50 $@
	@./run 100 $@

.PHONY: all koa toa
